version: '3.8'

services:
  empacotamento-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empacotamento-api
    ports:
      - "3000:3000"
    restart: unless-stopped
